---
title: "Exploratory Data Analysis"
output: pdf_document
---

```{r setup}
rm(list = ls())
require(readr)
require(tidyr)
require(dplyr)
require(knitr)
```

```{r}
data <- read.csv("data/processed/data.csv")

# We remove these columns because we want to be predicting the turnout
# rate solely from county demographics
data <- data %>% select(-c(X, State, County, fips))
head(data)
```

We have no categorical variables. For each of our continuous variables, we summarize the number of missing values, the mean, median, standard deviation, and interquartile range.

```{r}
predictors <- names(data)[names(data) != "turnout.rate"]
summary_table <- data.frame()

for (predictor in predictors) {
  column <- data[[predictor]]
  num_non_missing <- sum(!is.na(column))
  num_missing <- sum(is.na(column))
  mean_var <- mean(column, na.rm = TRUE)
  median_var <- median(column, na.rm = TRUE)
  sd_var <- sd(column, na.rm = TRUE)
  iqr_var <- IQR(column, na.rm = TRUE)

  summary_table <- rbind(summary_table, data.frame(
    Variable = predictor,
    Non_Missing = num_non_missing,
    Missing = num_missing,
    Mean = round(mean_var, 2),
    Median = round(median_var, 2),
    SD = round(sd_var, 2),
    IQR = round(iqr_var, 2)
  ))
}

kable(summary_table)
```


We also check that our hypothesis that the turnout rate can be predicted from county demographics is reasonable by fitting a linear regression model.
```{r}
lm_model <- lm(turnout.rate ~ ., data = data)
summary(lm_model)
```
